[workspace]
exclude = ["taffy", "Coplt.Com2"]
members = ["coplt_ui_rusty"]
resolver = "3"

[workspace.dependencies]
cocom = {path = "Coplt.Com2/cocom_rs"}
concat-idents = "1"
dashmap = "6.1"
etagere = "0.2"
taffy = {path = "taffy"}
