[package]
edition = "2024"
name = "coplt_ui_rusty"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
cocom = {workspace = true}
concat-idents = {workspace = true}
dashmap = {workspace = true}
etagere = {workspace = true}
taffy = {workspace = true}
